language: python

matrix:
  include:
    - os: linux
      sudo: false
      python: "2.7"

    - os: linux
      sudo: false
      python: "3.2"

    - os: linux
      sudo: false
      python: "3.3"

    - os: linux
      sudo: false
      python: "3.4"

    - os: linux
      sudo: false
      python: "3.5"

    - os: linux
      sudo: false
      python: "3.6"

    - os: osx
      language: generic
      python: "2.7"

    - os: osx
      language: generic
      python: "3.2"

    - os: osx
      language: generic
      python: "3.3"

    - os: osx
      language: generic
      python: "3.4"

    - os: osx
      language: generic
      python: "3.5"

    - os: osx
      language: generic
      python: "3.6"

script:
  - make run
